# -*- coding: utf-8 -*-
"""Transformer-Scratch Implementation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p_UQP0LgLeS9OL3MyOZo9ib_UZZRnCK8
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from einops import rearrange

class MultiHeadAttention(nn.Module):
    def __init__(self, embedd_dim, n_heads, bias=False ) -> None:
      # super(MyClass, self).__init__()
      super().__init__()

      if(embedd_dim % n_heads != 0):
          raise ValueError(
              f"embedding dimension = {embedd_dim} should be divisible by number of heads = {n_heads}"
          )

      self.embedd_dim = embedd_dim
      self.n_heads = n_heads
      self.head_dim = embedd_dim // n_heads

      self.query_vec = nn.Linear(embedd_dim, embedd_dim, bias=bias)
      self.key_vec = nn.Linear(embedd_dim, embedd_dim, bias=bias)
      self.value_vec = nn.Linear(embedd_dim, embedd_dim, bias=bias)

      self.out = nn.Linear(embedd_dim, embedd_dim, bias=bias)

    def forward(self, query, key, value, mask=None):
      query = self.query_vec(query)
      key = self.key_vec(key)
      value = self.value_vec(value)

      # input dim => (batch_size, seq_len, out_dim)

      # (batch_size, seq_len, out_dim) => (batch, n_heads, seq_len, out_dim)
      query = rearrange(query, "b n (h d) -> b h n d", h=self.n_heads)
      key = rearrange(key, "b n (h d) -> b h n d", h=self.n_heads)
      value = rearrange(value, "b n (h d) -> b h n d", h=self.n_heads)

      ## calculate attention score
      attention_score = (torch.matmul(query, key.transpose(-2, -1))) / (key.shape[-1] ** 0.5)

      if mask is not None:
        attention_score = attention_score.masked_fill(mask == 0, float("-inf"))

      attention_score = F.softmax(attention_score, dim=-1)

      context_vec = torch.matmul(attention_score, value)

      context_vec = rearrange(context_vec, "b h n d -> b n (h d)")

      output = self.out(context_vec)

      return output

"""### Test MultiHeadAttention Implementation"""

# Define parameters for testing
batch_size = 2
seq_len = 10
embedd_dim = 256
n_heads = 8

# Instantiate the MultiHeadAttention module
mha = MultiHeadAttention(embedd_dim=embedd_dim, n_heads=n_heads)

# Create dummy input tensors
query = torch.randn(batch_size, seq_len, embedd_dim)
key = torch.randn(batch_size, seq_len, embedd_dim)
value = torch.randn(batch_size, seq_len, embedd_dim)

# Create a dummy mask (optional, but good for testing masked attention)
# For simplicity, let's create a mask where some positions are blocked
mask = torch.ones(batch_size, n_heads, seq_len, seq_len)
mask[:, :, :, seq_len // 2:] = 0 # Block the second half of sequence for attention

print(f"Query shape: {query.shape}")
print(f"Key shape: {key.shape}")
print(f"Value shape: {value.shape}")
print(f"Mask shape: {mask.shape}\n")

# Perform the forward pass
output = mha(query, key, value, mask=mask)

# Print the output shape to verify
print(f"Output shape: {output.shape}")
print("Output (first batch, first 3 tokens, first 5 dimensions):\n", output[0, :3, :5])

attention_weights.sum(dim=-1)

## FNN Module

class FNN(nn.Module):
  def __init__(self, embedd_dim, bias=False):
    super().__init__()

    self.FF = nn.Sequential(
        nn.Linear(embedd_dim, 4 * embedd_dim, bias=bias),  # input_dim = 512 Hidden_layers neurons = 2048 output dim = 512
        nn.ReLU(),
        nn.Linear(4 * embedd_dim, embedd_dim, bias=bias)
    )

  def forward(self, x):
    return self.FF(x)

class Encoder(nn.Module):
  """
    Single Transformer Encoder Block.

    Components:
        - Multi-Head Self-Attention
        - Feed Forward Network (FFN)
        - Residual Connections
        - Layer Normalization
        - Dropout

    Args:
        embedd_dim (int):
            Dimension of token embeddings and hidden representations.
            Often referred to as d_model.

        n_heads (int):
            Number of attention heads used in
            multi-head self-attention.

        ff_dim (int):
            Hidden dimension of the Feed Forward Network.

        bias (bool, optional):
            Whether linear layers use bias terms.

            Default:
                False
    """
  def __init__(self, embedd_dim, n_heads, ff_dim, bias=False):
    super().__init__()


    self.mha = MultiHeadAttention(embedd_dim, n_heads, bias=bias)
    self.FF = FNN(embedd_dim, bias=bias)

    self.norm1 = nn.LayerNorm(embedd_dim)
    self.norm2 = nn.LayerNorm(embedd_dim)

    self.dropout = nn.Dropout(0.1)

  def forward(self, x, mask=None):
    """
    Forward pass of a Transformer Encoder Block.

    Args:
        x (Tensor):
            Input token embeddings.

            Shape:
                (batch_size, seq_len, embedd_dim)

            Example:
                (32, 128, 512)

        mask (Tensor, optional):
            Padding mask used to ignore
            padded tokens during attention.

            Shape:
                (batch_size, 1, 1, seq_len)

            Default:
                None

    Returns:
        Tensor:
            Contextualized token representations
            produced by the encoder block.

            Shape:
                (batch_size, seq_len, embedd_dim)

    Processing Steps:
        1. Multi-Head Self-Attention
           Q = K = V = x

        2. Residual Connection + LayerNorm

        3. Feed Forward Network (FFN)

        4. Residual Connection + LayerNorm

        5. Return encoder representations
    """
    x = x + self.dropout(self.mha(x, x, x, mask))

    ff_out = self.FF(x)

    x = x + self.dropout(self.norm2(ff_out))

    return x

class Decoder(nn.Module):
  def __init__(self, embedd_dim, n_heads, drop_out=0.1, bias = False):
    """
    Single Transformer Decoder Block.

    Components:
        - Masked Multi-Head Self-Attention
        - Encoder-Decoder (Cross) Attention
        - Feed Forward Network (FFN)
        - Residual Connections
        - Layer Normalization
        - Dropout

    Args:
        embedd_dim (int):
            Dimension of token embeddings and hidden representations.
            Often called d_model in Transformer literature.

        n_heads (int):
            Number of attention heads used in multi-head attention.

        drop_out (float, optional):
            Dropout probability applied after attention
            and feed-forward layers.
            Default: 0.1

        bias (bool, optional):
            Whether linear layers inside attention and
            feed-forward networks use bias terms.
            Default: False
    """
    super().__init__()

    self.mha = MultiHeadAttention(embedd_dim, n_heads, bias)
    self.FF = FNN(embedd_dim, bias)
    self.norm1 = nn.LayerNorm(embedd_dim)
    self.norm2 = nn.LayerNorm(embedd_dim)
    self.norm3 = nn.LayerNorm(embedd_dim)
    self.dropout = nn.Dropout(drop_out)

  def forward(self, x, encoder_out, mask, tgt_mask):
    """
    Forward pass of a Transformer Decoder Block.

    Args:
        x (Tensor):
            Target sequence embeddings.

            Shape:
                (batch_size, target_seq_len, embedd_dim)

            Example:
                (32, 20, 512)

        encoder_out (Tensor):
            Output generated by the encoder.
            Used as keys and values in cross-attention.

            Shape:
                (batch_size, source_seq_len, embedd_dim)

            Example:
                (32, 30, 512)

        mask (Tensor):
            Source padding mask.
            Prevents attention from attending
            to padding tokens in the source sequence.

            Shape:
                (batch_size, 1, 1, source_seq_len)

        tgt_mask (Tensor):
            Target causal/look-ahead mask.
            Prevents positions from attending
            to future tokens.

            Shape:
                (batch_size, 1, target_seq_len, target_seq_len)

    Returns:
        Tensor:
            Decoder output after masked self-attention,
            cross-attention, and feed-forward network.

            Shape:
                (batch_size, target_seq_len, embedd_dim)

    Processing Steps:
        1. Masked Self-Attention
           Q = K = V = x

        2. Residual Connection + LayerNorm

        3. Cross-Attention
           Q = decoder output
           K = encoder output
           V = encoder output

        4. Residual Connection + LayerNorm

        5. Feed Forward Network (FFN)

        6. Residual Connection + LayerNorm

        7. Return decoder representation
    """
    attention = self.mha(x, x, x, tgt_mask)
    x = x + self.dropout(self.norm1(attention))
    cross_attention = self.mha(x, encoder_out, encoder_out, mask)
    x = x + self.dropout(self.norm2(cross_attention))
    ff_out = self.FF(x)
    x = x + (self.norm3(self.dropout(ff_out)))

    return x

class PositionalEncoding(nn.Module):
  def __init__(self, embedd_dim, max_len=5000):
    super().__init__()

    self.pos = torch.arange(0, max_len)
    self.theta = 1 / ((10000 ** torch.arange(0, embedd_dim, 2)) / embedd_dim)

    positional_encodings = torch.zeros(max_len, embedd_dim)
    positional_encodings[:, 0::2] = torch.sin(self.pos[:, None] / self.theta)
    positional_encodings[:, 1::2] = torch.cos(self.pos[:, None] / self.theta)

    self.register_buffer("positional_encodings", positional_encodings)

  def forward(self, x):
    batch_size, seq_len, embed_size = x.shape
    return x + self.positional_encodings[:seq_len, :]

def get_mask(src, tgt):

  src_mask = (src != 0) [:, None, None, :]  # (batch_size, seq_len) => (batch_size, n_heads, query_len, key_len)
  tgt_mask = (tgt != 0) [:, None, :, None]

  seq_len = tgt_mask.shape[-2]

  causal_mask = torch.tril(torch.ones(seq_len, seq_len)).bool()  # causal_mack (look ahead mask ) it is making the decoder autoregressive
  final_tgt_mask = causal_mask & tgt_mask

  return src_mask, final_tgt_mask

class Transformer(nn.Module):
  def __init__(
      self,
      src_vocab_size,
      embedd_dim,
      tgt_vocab_size,
      max_seq_len,
      n_heads,
      dropout_ratio,
      bias ,
      n_encoders,
      n_decoders
  ):
    super().__init__()
    self.encoder_embedd = nn.Embedding(src_vocab_size, embedd_dim)
    self.decoder_embedd = nn.Embedding(tgt_vocab_size, embedd_dim)
    self.positional_encoding = PositionalEncoding(embedd_dim, max_seq_len)

    # create multiple encoder decoder layers
    self.encoder = nn.ModuleList([Encoder(embedd_dim, n_heads, dropout_ratio, bias) for _ in range(n_encoders)])
    self.decoder = nn.ModuleList([Decoder(embedd_dim, n_heads, dropout_ratio, bias) for _ in range(n_decoders)])

    self.dropout = nn.Dropout(dropout_ratio)

    self.FF = nn.Linear(embedd_dim, tgt_vocab_size)



  def forward(self, src, tgt):
    src_mask,tgt_mask = get_mask(src, tgt)

    encoder_embed = self.dropout(self.positional_encoding(self.encoder_embedd(src)))
    decoder_embed = self.dropout(self.positional_encoding(self.decoder_embedd(tgt)))

    encoder_output = encoder_embed
    for encoder_layer in self.encoder:
      encoder_output = encoder_layer(encoder_output, src_mask)

    decoder_output = decoder_embed
    for decoder_layer in self.decoder:
      decoder_output = decoder_layer(decoder_output, encoder_output, src_mask, tgt_mask)

    output = self.FF(decoder_output)

    return output

model = Transformer(
    src_vocab_size=100,
    tgt_vocab_size=120,
    embedd_dim=64,
    max_seq_len=50,
    n_heads=8,
    dropout_ratio=0.1,
    bias=True,
    n_encoders=2,
    n_decoders=2
)

print(model)

# forward pass
batch_size = 4
src_len = 10
tgt_len = 8

src = torch.randint(1, 100, (batch_size, src_len))
tgt = torch.randint(1, 120, (batch_size, tgt_len))

output = model(src, tgt)
print(output.shape)

output.shape

## check backward pass
target = torch.randint(0, 120, (4, 8))

loss_fn = nn.CrossEntropyLoss()

loss = loss_fn(
    output.reshape(-1, 120),
    target.reshape(-1)
)

loss.backward()

print(loss.item())

# see target mask

_, tgt_mask = get_mask(
    torch.tensor([[1,2,3,4]]),
    torch.tensor([[1,2,3,4]])
)

print(tgt_mask[0,0].int())

