import torch
import torch.nn as nn
import torch.nn.functional as F
from einops import rearrange


class Decoder(nn.Module):
  def __init__(self, embedd_dim, n_heads, drop_out=0.1, bias = False):
    """
    Single Transformer Decoder Block.

    Components:
        - Masked Multi-Head Self-Attention
        - Encoder-Decoder (Cross) Attention
        - Feed Forward Network (FFN)
        - Residual Connections
        - Layer Normalization
        - Dropout

    Args:
        embedd_dim (int):
            Dimension of token embeddings and hidden representations.
            Often called d_model in Transformer literature.

        n_heads (int):
            Number of attention heads used in multi-head attention.

        drop_out (float, optional):
            Dropout probability applied after attention
            and feed-forward layers.
            Default: 0.1

        bias (bool, optional):
            Whether linear layers inside attention and
            feed-forward networks use bias terms.
            Default: False
    """
    super().__init__()

    self.mha = MultiHeadAttention(embedd_dim, n_heads, bias)
    self.FF = FNN(embedd_dim, bias)
    self.norm1 = nn.LayerNorm(embedd_dim)
    self.norm2 = nn.LayerNorm(embedd_dim)
    self.norm3 = nn.LayerNorm(embedd_dim)
    self.dropout = nn.Dropout(drop_out)

  def forward(self, x, encoder_out, mask, tgt_mask):
    """
    Forward pass of a Transformer Decoder Block.

    Args:
        x (Tensor):
            Target sequence embeddings.

            Shape:
                (batch_size, target_seq_len, embedd_dim)

            Example:
                (32, 20, 512)

        encoder_out (Tensor):
            Output generated by the encoder.
            Used as keys and values in cross-attention.

            Shape:
                (batch_size, source_seq_len, embedd_dim)

            Example:
                (32, 30, 512)

        mask (Tensor):
            Source padding mask.
            Prevents attention from attending
            to padding tokens in the source sequence.

            Shape:
                (batch_size, 1, 1, source_seq_len)

        tgt_mask (Tensor):
            Target causal/look-ahead mask.
            Prevents positions from attending
            to future tokens.

            Shape:
                (batch_size, 1, target_seq_len, target_seq_len)

    Returns:
        Tensor:
            Decoder output after masked self-attention,
            cross-attention, and feed-forward network.

            Shape:
                (batch_size, target_seq_len, embedd_dim)

    Processing Steps:
        1. Masked Self-Attention
           Q = K = V = x

        2. Residual Connection + LayerNorm

        3. Cross-Attention
           Q = decoder output
           K = encoder output
           V = encoder output

        4. Residual Connection + LayerNorm

        5. Feed Forward Network (FFN)

        6. Residual Connection + LayerNorm

        7. Return decoder representation
    """
    attention = self.mha(x, x, x, tgt_mask)
    x = x + self.dropout(self.norm1(attention))
    cross_attention = self.mha(x, encoder_out, encoder_out, mask)
    x = x + self.dropout(self.norm2(cross_attention))
    ff_out = self.FF(x)
    x = x + (self.norm3(self.dropout(ff_out)))

    return x
